- Formula/sbomqs.rb
- README.md
> Fixes after testing and readme update

- Formula/sbomqs.rb
Add support for `sbomqs` version v0.0.8
> Support v0.0.8 sbomqs

- Formula/sbomqs.rb
> Add v0.0.9 support

- Formula/sbomqs.rb
- Added support for mac and linux arm 
- Add support for v0.0.10
> v0.0.10 support

- Formula/sbomex.rb
> Fix ruby syntax

- Formula/sbomex.rb
> Fix CGO issue with sbomex

- Formula/sbomgr.rb
Align all settings with sbomqs.
> align with sbomqs

- Formula/sbomqs.rb
Add support for sbomqs vs 0.0.11
> add sbomqs v0.0.11

- Formula/sbomqs.rb
> sbomqs v0.0.12

- Formula/sbomqs.rb
> support sbomqs v0.0.13

- Formula/sbomex.rb
> [sbomex v0.0.3] Release Update

- Formula/sbomqs.rb
> sbomqs v0.0.14

- Formula/sbomex.rb
> [NO-TKT] sbomex v0.0.4 hotfix

- Formula/sbomqs.rb
> sbomqs v0.0.15

- Formula/sbomasm.rb
- Formula/sbomqs.rb
> sbomqs and sbomasm

- Formula/sbomgr.rb
- Formula/sbomqs.rb
sbomqs release v0.0.17 
sbomgr release v0.0.5
> Add new versions

- Formula/sbomex.rb
Homebrew upgrade to sbomex v0.0.5
> [NO-TKT] sbomex v0.0.5 update

- Formula/sbomqs.rb
> [NO-TKT] sbomqs v0.0.18 release

- Formula/sbomgr.rb
- sbomgr v0.0.6 release updates
> [NO-TKT] sbomgr v0.0.6 release

- Formula/sbomasm.rb
> [NO-TKT] sbomasm v0.0.4 release

- Formula/sbomex.rb
> [NO-TKT] sbomex v0.0.6 release

- Formula/sbomasm.rb
- Formula/sbomex.rb
- Formula/sbomgr.rb
- Formula/sbomqs.rb
- sbomex v0.0.5
- sbomgr v0.0.7
- sbomqs v0.0.19
- sbomasm v0.0.5
> [NO-TKT] sbomex, sbomgr, sbomqs, sbomasm releases

- Formula/sbomex.rb
> [NO-TKT] sbomex v0.0.9 Release

- Formula/sbomasm.rb
> [NO-TKT] sbomasm v0.0.7 release

- Formula/sbomgr.rb
> [NO-TKT] sbomgr v0.0.10 release

- Formula/sbomex.rb
> [NO-TKT] sbomex v0.0.10 release part-2

- Formula/sbomasm.rb
- Formula/sbomex.rb
- Formula/sbomgr.rb
- Formula/sbomqs.rb
> [NO-TKT] all weekly releases

- Formula/sbomasm.rb
- Formula/sbomex.rb
- Formula/sbomgr.rb
- Formula/sbomqs.rb
- sbomex v0.0.12
- sbomasm v0.0.9
- sbomgr v0.0.12
- sbomqs v0.0.24
> [NO-TKT] Oct 26 all releases

- Formula/sbomasm.rb
- Formula/sbomgr.rb
sbomasm v0.0.12
sbomgr v0.0.15
> [NO-TKT] sbomasm, sbomgr releases

- Formula/sbomqs.rb
> update sbomqs v0.0.29

- Formula/sbomex.rb
- Formula/sbomqs.rb
- sbomex v0.0.15
- sombqs v0.0.30
> [RELEASE] Jan 27th releases

- Formula/sbomqs.rb
- Add support for sbomqs v0.1.0
> sbomqs v0.1.0

- Formula/sbomqs.rb
Reverts interlynk-io/homebrew-interlynk#55
> Revert "sbomqs v0.1.0"

- Formula/sbomqs.rb
> release sbomqs v0.1.1

- Formula/sbomqs.rb
> sbomqs v0.1.2

- Formula/sbomqs.rb
> Release sbomqs v0.1.4

- Formula/sbomqs.rb
> sbomqs v0.1.5

- Formula/sbomasm.rb
> [NO-TKT] sbomasm release v0.1.3

- Formula/sbomqs.rb
> update sbomqs v0.1.8

- Formula/sbomex.rb
> [NO-TKT] sbomex v0.1.0 release

- Formula/sbomqs.rb
> release v0.1.9

- Formula/sbomqs.rb
> fixed typp

- Formula/sbomgr.rb
> release sbomgr v0.1.2

- Formula/sbomgr.rb
> release sbomgr v0.1.3

- Formula/sbomasm.rb
> release sbomasm v0.1.8

- Formula/sbomasm.rb
> release sbomasm v0.1.9

- Formula/sbomqs.rb
> Add sbomqs v022

- Formula/sbomqs.rb
> sbomqs v1.0.0

- Formula/sbommv.rb
This PR adds the following things:
- Add checksums of binaries
> add cheksum

- Formula/sbomqs.rb
> sbomqs v1.0.2

- Formula/sbomqs.rb
- update checksum for sbomqs v1.0.3
> update checksum for sbomqs v1.0.3

- Formula/sbomasm.rb
- update checksum for sbomasm v1.0.1
> update checksum for sbomasm v1.0.1

- Formula/sbommv.rb
- Update the checksums for sbommv:v0.0.4
> add checksum for sbommv:v0.0.4 release

- Formula/sbommv.rb
- It updates the sbommv:v0.0.5 checksums
> add sbommv:v0.0.5 checksum

- Formula/sbomqs.rb
- It updates the sbomqs:v1.0.5 checksums
> add sbomqs:v1.0.5 checksum

- Formula/sbomasm.rb
- It updates the sbomasm:v1.0.3 checksums
> add sbomasm:v1.0.3 checksum

- Formula/sbomqs.rb
This PR updates the following changes:
- Updates the sbomqs checksum for v1.0.6
> add sbomqs v1.0.6 checksum

- Formula/sbommv.rb
This PR updates the following changes:
- update homebre formula for sbommv:v0.0.6
> update sbommv v0.0.6 formulae

- Formula/sbomasm.rb
This PR updates the following changes:
- Updates the sbomasm:v1.0.4 formula
> update sbomasm v1.0.4 formulae

- Formula/sbomqs.rb
This PR updates following changes:
- Updates sbomqs:v1.0.9 checksum
> update sbomqs v1.0.9 checksum

- Formula/sbommv.rb
This PR updates the following changes:
- Updates the sbommv:v0.0.8 checksums
> update sbommv v.0.8 checksum

- Formula/sbomasm.rb
This PR ads the following changes:
- updates the formula for sbomasm:v1.0.5
> update sbomasm v1.0.5 formula

- Formula/sbomqs.rb
- update the `sbomqs:v1.1.0` formula
> update sbomqs:v1.1.0 formula
